
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import static java.lang.Character.isDigit;
import static java.lang.Character.isLetter;
import static java.lang.Character.isLowerCase;
import static java.lang.Character.isUpperCase;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author jnogueira
 */
public class EditarDados extends javax.swing.JFrame {
    /**
     * Creates new form FormRegisto
     */
    public EditarDados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ctxPassword = new javax.swing.JPasswordField();
        ctxRePassword = new javax.swing.JPasswordField();
        ctxNif = new javax.swing.JTextField();
        ctxMorada = new javax.swing.JTextField();
        ctxEmail = new javax.swing.JTextField();
        ctxNome = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btxRegistarUtilizador = new javax.swing.JButton();
        ctxLoginUser = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        ctxLogin = new javax.swing.JLabel();
        ctxTelefone = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Formulário de Registo de Utilizadores");

        botaoSair.setBackground(new java.awt.Color(255, 51, 51));
        botaoSair.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botaoSair.setForeground(new java.awt.Color(255, 255, 255));
        botaoSair.setText("Voltar atrás");
        botaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSairActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Nome");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Email");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Morada");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("NIF");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Password");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Repita Password");

        ctxPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        ctxRePassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        ctxNif.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        ctxMorada.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        ctxEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ctxEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctxEmailActionPerformed(evt);
            }
        });

        ctxNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ctxNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctxNomeActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel7.setText("Registo de Utilizador");

        btxRegistarUtilizador.setBackground(new java.awt.Color(102, 255, 102));
        btxRegistarUtilizador.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btxRegistarUtilizador.setText("Validar Dados");
        btxRegistarUtilizador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btxRegistarUtilizadorActionPerformed(evt);
            }
        });

        ctxLoginUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ctxLoginUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctxLoginUserActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Telefone");

        ctxLogin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ctxLogin.setText("Login");

        ctxTelefone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ctxTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ctxNif, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(botaoSair))
                                    .addGap(18, 18, 18))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ctxPassword)
                                .addComponent(ctxRePassword)
                                .addComponent(btxRegistarUtilizador, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(100, 100, 100)
                                .addComponent(ctxNome, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ctxEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(87, 87, 87)
                                    .addComponent(ctxMorada, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(ctxLogin)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ctxLoginUser, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ctxNome, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ctxEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ctxMorada, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(ctxTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ctxNif, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ctxLoginUser, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(ctxLogin))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ctxPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ctxRePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botaoSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btxRegistarUtilizador))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSairActionPerformed
        MenuOpcoes menuOp = new MenuOpcoes();
        this.dispose(); // fecha a janela atual
        menuOp.setVisible(true);
    }//GEN-LAST:event_botaoSairActionPerformed

    public static void mensagemErro(String erro){
        JOptionPane.showMessageDialog(null, erro, "Erro validação", JOptionPane.ERROR_MESSAGE);
    }
    
    
    private void btxRegistarUtilizadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btxRegistarUtilizadorActionPerformed
        String nome = ctxNome.getText();
        String email = ctxEmail.getText();
        String morada = ctxMorada.getText();
        String telefone = ctxTelefone.getText();
        String nif = ctxNif.getText();
        String pass = ctxPassword.getText();
        String repass = ctxRePassword.getText();
        String login = ctxLoginUser.getText();
        // DONE - nome >= 2 caracteres
        // DONE - email tem de ter 1 @ e 1 . após o @
        // DONE - morada tem de ter >5 caracteres
        // DONE - telefone 9 caracteres que sejam dígitos
        // DONE - NIF 9 caracteres que sejam dígitos
        // DONE - pass e rePass têm de ser iguais
        // DONE - pass 8 ou + caracteres, 1 ou + minúsculas, 1 ou + algarismos,
        // DONE - 1 ou + maiúsculas, 1 ou + caracteres especiais
        
        if (nome.equals("")||email.equals("")||morada.equals("")|| 
                telefone.equals("")||nif.equals("")||
                pass.equals("")||repass.equals("")){
            mensagemErro("Preencha todos os campos!");
        }else{
            if(!validaCampoNumerico(telefone)){
                mensagemErro("O telefone deverá ter 9 digitos.");
            }else{
                if(!validaCampoNumerico(nif)){
                    mensagemErro("O NIF deverá ter 9 digitos.");
                }else{
                    if(nome.length()<2)
                        mensagemErro("Campo Nome deverá ter mais de dois caracteres.");
                    else
                        if(!validaCaracteres(nome)){
                            mensagemErro("Campo Nome tem caracteres inválidos.");
                    }else{
                        if (morada.length()<6){
                            mensagemErro("Morada deverá ter mais de 5 caracteres.");
                        }else{
                            if (!verificaPass(pass)){
                                mensagemErro("Password não é segura o suficiente.");    
                            }else{
                                if (pass.compareTo(repass)!=0){
                                    mensagemErro("Password tem de ser igual.");
                                }else{
                                    if(!validaEmail(email)){
                                        mensagemErro("Email não é valido.");                                    
                                    }else{
                                        registaUtilizador(nome,email,morada,telefone,nif,pass,login);
                                        Login lf = new Login();
                                        this.setVisible(false);
                                        lf.setVisible(true);
                                        }
                                    }
                                }
                            }   
                        }
                    }   
                }
            }
        

        
        
        
        
        
    }//GEN-LAST:event_btxRegistarUtilizadorActionPerformed

    private void ctxLoginUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctxLoginUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctxLoginUserActionPerformed

    private void ctxNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctxNomeActionPerformed
        File ficheiro = new File("UtilizadoresRegistados\\", MenuOpcoes.login);
        try {
            FileWriter fw = new FileWriter(ficheiro,true);
            BufferedWriter bw = new BufferedWriter(fw);
            FileReader fr = new FileReader(ficheiro);
            BufferedReader br = new BufferedReader(fr);            
            JOptionPane.showMessageDialog(null, "Nome teste");
        } catch (IOException ex) {
            Logger.getLogger(EditarDados.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_ctxNomeActionPerformed

    private void ctxEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctxEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctxEmailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormRegisto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormRegisto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormRegisto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormRegisto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormRegisto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoSair;
    private javax.swing.JButton btxRegistarUtilizador;
    private javax.swing.JTextField ctxEmail;
    private javax.swing.JLabel ctxLogin;
    private javax.swing.JTextField ctxLoginUser;
    private javax.swing.JTextField ctxMorada;
    private javax.swing.JTextField ctxNif;
    private javax.swing.JTextField ctxNome;
    private javax.swing.JPasswordField ctxPassword;
    private javax.swing.JPasswordField ctxRePassword;
    private javax.swing.JTextField ctxTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables

    private boolean validaCampoNumerico(String valor) {
        int x, contador=0,t = valor.length();
        char c;
        if (t!=9)
            return false;
        else{
            for(x=0;x<t;x++){
                c = valor.charAt(x);
                if(isDigit(c))
                    contador++;
            }    
            if(t!=contador)
                return false;
            }
        return true;
    }

    private boolean validaCaracteres(String palavra) {
        int x, t = palavra.length();
        char c;
        for(x=0;x<t;x++){
            c = palavra.charAt(x);
            if(!isLetter(c)&&(c != ' ')){
                return false;  
            }
        }
        return true;
    }
        

    private boolean validaEmail(String email) {
        int i, ii;
        i = email.indexOf(' ');
        if (i != -1){
            return false;
        }
        i = email.indexOf('@');
        if (i == -1){
            return false;
        }else{
            ii = email.indexOf('@',(i+1));
            if (ii != -1){
                return false;
            }
        }
        i = email.indexOf('.',i);
        if(i == -1){
            return false;
        }
        return true;
    }

    @SuppressWarnings("empty-statement")
    private boolean verificaPass(String pass) {
        int i, x = 0, contMin = 0, contAlg = 0, contMaiusc = 0, contEsp = 0;
        char c;
        i = pass.indexOf(' ');
        if (i != -1){
            return false;
        }
        i = pass.length();
        if (i <8){
            return false;
        }
        for(x = 0 ;x < i ;x++){
            c = pass.charAt(x);
            if (isLowerCase(c)){
                contMin++;
            }else{
                if (isUpperCase(c)){
                    contMaiusc++;
                }else{
                    if (isDigit(c)){
                        contAlg++;
                    }else{
                        contEsp++;
                    }
                }        
            }
        }
        if ((contMin<1) || (contMaiusc<1) || (contAlg<1) || (contEsp<1)){
            return false;
        }
        return true;
    }

    private void registaUtilizador(String nome, String email, String morada, String telefone, String nif, String pass, String login) {
        File ficheiro = new File("C:\\Users\\jnogueira\\Desktop\\0816 - Java\\SistemasDeLogIn\\SistemaLogin\\UtilizadoresRegistados", login + ".txt");
        if(!ficheiro.exists()){
            try {
                ficheiro.createNewFile();
                FileWriter fw = new FileWriter(ficheiro,true);
                BufferedWriter bw = new BufferedWriter(fw);
                bw.write(pass);bw.newLine();
                bw.write(login);bw.newLine();
                bw.write(nome);bw.newLine();
                bw.write(email);bw.newLine();
                bw.write(morada);bw.newLine();
                bw.write(nif);bw.newLine();
                bw.write(telefone);bw.newLine();
                bw.newLine();
                bw.close();
                fw.close();
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }
    }    
}
