
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author jnogueira
 */
public class MenuOpcoes extends javax.swing.JFrame {

    /**
     * Creates new form MenuOpcoes
     */
    public static String login = Login.login;
    Login log;
    public MenuOpcoes() {
        initComponents();
        if (log == null)
            log = new Login();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MostrarUtilizadoresRegistados = new javax.swing.JButton();
        EliminarUtilizador = new javax.swing.JButton();
        VisualizarDadosUtilizadores = new javax.swing.JButton();
        EditarDadosUtilizador = new javax.swing.JButton();
        TerminarSessao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MostrarUtilizadoresRegistados.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MostrarUtilizadoresRegistados.setText("Mostrar Utilizadores Registados");
        MostrarUtilizadoresRegistados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarUtilizadoresRegistadosActionPerformed(evt);
            }
        });

        EliminarUtilizador.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EliminarUtilizador.setText("Eliminar Utilizador");
        EliminarUtilizador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarUtilizadorActionPerformed(evt);
            }
        });

        VisualizarDadosUtilizadores.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        VisualizarDadosUtilizadores.setText("Visualizar Dados Utilizadores");
        VisualizarDadosUtilizadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisualizarDadosUtilizadoresActionPerformed(evt);
            }
        });

        EditarDadosUtilizador.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EditarDadosUtilizador.setText("Editar Dados Utilizador");
        EditarDadosUtilizador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarDadosUtilizadorActionPerformed(evt);
            }
        });

        TerminarSessao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TerminarSessao.setText("Terminar sessão");
        TerminarSessao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TerminarSessaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MostrarUtilizadoresRegistados)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(EliminarUtilizador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(VisualizarDadosUtilizadores, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                        .addComponent(EditarDadosUtilizador, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)))
                .addContainerGap(191, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TerminarSessao)
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(MostrarUtilizadoresRegistados, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(EliminarUtilizador, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(VisualizarDadosUtilizadores, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(EditarDadosUtilizador, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addComponent(TerminarSessao, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MostrarUtilizadoresRegistadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarUtilizadoresRegistadosActionPerformed
        File ficheiro = new File("UtilizadoresRegistados\\");
        File [] listaUtilizadores = ficheiro.listFiles();        
        System.out.println(">>> Utilizadores Registados <<<");
        for(int i=0;i<listaUtilizadores.length;i++){
            System.out.println(listaUtilizadores[i].getName().replace(".txt", ""));
        }
    }//GEN-LAST:event_MostrarUtilizadoresRegistadosActionPerformed

    private void EliminarUtilizadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarUtilizadorActionPerformed
        File ficheiro = new File("UtilizadoresRegistados\\", login);
        File ficheiroEliminado = new File("UtilizadoresEliminados\\", login);
        try {
            ficheiroEliminado.createNewFile();
            FileWriter fwEliminado = new FileWriter(ficheiroEliminado,true);
            BufferedWriter bwEliminado = new BufferedWriter(fwEliminado);
            FileReader fr = new FileReader(ficheiro);
            BufferedReader br = new BufferedReader(fr);
            while(br.ready()){
                bwEliminado.write(br.readLine());
                bwEliminado.newLine();
        }
        br.close();
        fr.close();
        bwEliminado.close();
        fwEliminado.close();
        } catch (IOException ex) {
            Logger.getLogger(MenuOpcoes.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(null, "Utilizador eliminado.", "Informação", JOptionPane.ERROR_MESSAGE);
        Login lf = new Login();
        this.setVisible(false);
        lf.setVisible(true); 
    }//GEN-LAST:event_EliminarUtilizadorActionPerformed

    private void VisualizarDadosUtilizadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisualizarDadosUtilizadoresActionPerformed
        File ficheiro = new File("UtilizadoresRegistados\\", login);
        String [] items = {"Nome: ","Email: ", "Morada: ","Telefone: ", "NIF: ", "Login: ", "Password: "}; 
        try{
            FileReader fr = new FileReader(ficheiro);
            BufferedReader br = new BufferedReader(fr);
            int i = 0;
            while(br.ready()){
                System.out.print(items[i]);
                String linha = br.readLine();
                System.out.println(linha);
                i += 1;
            }
            br.close();
            fr.close();
        }catch (FileNotFoundException ex){
                ex.printStackTrace();
        }catch (IOException ioe){
                ioe.printStackTrace();
        }
    }//GEN-LAST:event_VisualizarDadosUtilizadoresActionPerformed

    private void EditarDadosUtilizadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarDadosUtilizadorActionPerformed
        EditarDados ed = new EditarDados();
        this.setVisible(false);
        ed.setVisible(true); 
    }//GEN-LAST:event_EditarDadosUtilizadorActionPerformed

    private void TerminarSessaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TerminarSessaoActionPerformed
        Login lf = new Login();
        this.setVisible(false);
        lf.setVisible(true);        
    }//GEN-LAST:event_TerminarSessaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuOpcoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuOpcoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuOpcoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuOpcoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuOpcoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EditarDadosUtilizador;
    private javax.swing.JButton EliminarUtilizador;
    private javax.swing.JButton MostrarUtilizadoresRegistados;
    private javax.swing.JButton TerminarSessao;
    private javax.swing.JButton VisualizarDadosUtilizadores;
    // End of variables declaration//GEN-END:variables
}
